<?php

namespace Modules\Inventory\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Inventory\Models\InventoryItem;
use Modules\Inventory\Models\ItemCategory;
use Modules\Users\Models\User;
use Modules\Companies\Models\Company;
use Modules\Suppliers\Models\Supplier;

class InventoryItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get required data
        $user = User::first();
        $company = Company::first();
        $supplier = Supplier::first();

        if (!$user || !$company) {
            $this->command->warn('⚠️  Users or Companies not found. Please seed Users and Companies modules first.');
            return;
        }

        $inventoryItems = [
            [
                'company_id' => $company->id,
                'item_number' => 'INV-001',
                'item_name_ar' => 'كيبورد لاسلكي',
                'item_name_en' => 'Wireless Keyboard',
                'barcode' => '1111111111111',
                'model' => 'K380',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 150.00,
                'minimum_limit' => 20.00,
                'reorder_limit' => 30.00,
                'unit_price' => 85.00,
                'first_purchase_price' => 85.00,
                'second_purchase_price' => 82.00,
                'third_purchase_price' => 80.00,
                'first_sale_price' => 110.00,
                'second_sale_price' => 105.00,
                'third_sale_price' => 100.00,
                'notes' => 'Bluetooth wireless keyboard compatible with multiple devices',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-002',
                'item_name_ar' => 'ماوس بصري',
                'item_name_en' => 'Optical Mouse',
                'barcode' => '2222222222222',
                'model' => 'M100',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 200.00,
                'minimum_limit' => 25.00,
                'reorder_limit' => 40.00,
                'unit_price' => 35.00,
                'first_purchase_price' => 35.00,
                'second_purchase_price' => 33.00,
                'third_purchase_price' => 32.00,
                'first_sale_price' => 45.00,
                'second_sale_price' => 43.00,
                'third_sale_price' => 40.00,
                'notes' => 'USB optical mouse with ergonomic design',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-003',
                'item_name_ar' => 'كابل HDMI',
                'item_name_en' => 'HDMI Cable',
                'barcode' => '3333333333333',
                'model' => 'HDMI-2M',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 100.00,
                'minimum_limit' => 15.00,
                'reorder_limit' => 25.00,
                'unit_price' => 25.00,
                'first_purchase_price' => 25.00,
                'second_purchase_price' => 24.00,
                'third_purchase_price' => 23.00,
                'first_sale_price' => 35.00,
                'second_sale_price' => 33.00,
                'third_sale_price' => 30.00,
                'notes' => '2-meter HDMI cable for high-definition video transmission',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-004',
                'item_name_ar' => 'طابعة ليزر',
                'item_name_en' => 'Laser Printer',
                'barcode' => '4444444444444',
                'model' => 'LaserJet Pro',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 25.00,
                'minimum_limit' => 5.00,
                'reorder_limit' => 8.00,
                'unit_price' => 1200.00,
                'first_purchase_price' => 1200.00,
                'second_purchase_price' => 1180.00,
                'third_purchase_price' => 1150.00,
                'first_sale_price' => 1500.00,
                'second_sale_price' => 1450.00,
                'third_sale_price' => 1400.00,
                'notes' => 'Monochrome laser printer with network connectivity',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-005',
                'item_name_ar' => 'خرطوشة حبر أسود',
                'item_name_en' => 'Black Ink Cartridge',
                'barcode' => '5555555555555',
                'model' => 'HP-85A',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 80.00,
                'minimum_limit' => 10.00,
                'reorder_limit' => 20.00,
                'unit_price' => 180.00,
                'first_purchase_price' => 180.00,
                'second_purchase_price' => 175.00,
                'third_purchase_price' => 170.00,
                'first_sale_price' => 220.00,
                'second_sale_price' => 210.00,
                'third_sale_price' => 200.00,
                'notes' => 'Original black toner cartridge for LaserJet printers',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-006',
                'item_name_ar' => 'محول USB',
                'item_name_en' => 'USB Hub',
                'barcode' => '6666666666666',
                'model' => 'USB-HUB-4',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 60.00,
                'minimum_limit' => 10.00,
                'reorder_limit' => 15.00,
                'unit_price' => 45.00,
                'first_purchase_price' => 45.00,
                'second_purchase_price' => 43.00,
                'third_purchase_price' => 42.00,
                'first_sale_price' => 60.00,
                'second_sale_price' => 57.00,
                'third_sale_price' => 55.00,
                'notes' => '4-port USB 3.0 hub with LED indicators',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-007',
                'item_name_ar' => 'سماعات رأس',
                'item_name_en' => 'Headphones',
                'barcode' => '7777777777777',
                'model' => 'HD-450BT',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 40.00,
                'minimum_limit' => 8.00,
                'reorder_limit' => 12.00,
                'unit_price' => 250.00,
                'first_purchase_price' => 250.00,
                'second_purchase_price' => 245.00,
                'third_purchase_price' => 240.00,
                'first_sale_price' => 320.00,
                'second_sale_price' => 310.00,
                'third_sale_price' => 300.00,
                'notes' => 'Wireless Bluetooth headphones with noise cancellation',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-008',
                'item_name_ar' => 'كاميرا ويب',
                'item_name_en' => 'Webcam',
                'barcode' => '8888888888888',
                'model' => 'C920',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 30.00,
                'minimum_limit' => 5.00,
                'reorder_limit' => 10.00,
                'unit_price' => 180.00,
                'first_purchase_price' => 180.00,
                'second_purchase_price' => 175.00,
                'third_purchase_price' => 170.00,
                'first_sale_price' => 230.00,
                'second_sale_price' => 220.00,
                'third_sale_price' => 210.00,
                'notes' => 'Full HD 1080p webcam with built-in microphone',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-009',
                'item_name_ar' => 'قرص صلب خارجي',
                'item_name_en' => 'External Hard Drive',
                'barcode' => '9999999999999',
                'model' => 'WD-1TB',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 20.00,
                'minimum_limit' => 3.00,
                'reorder_limit' => 5.00,
                'unit_price' => 220.00,
                'first_purchase_price' => 220.00,
                'second_purchase_price' => 215.00,
                'third_purchase_price' => 210.00,
                'first_sale_price' => 280.00,
                'second_sale_price' => 270.00,
                'third_sale_price' => 260.00,
                'notes' => '1TB portable external hard drive with USB 3.0',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'company_id' => $company->id,
                'item_number' => 'INV-010',
                'item_name_ar' => 'شاحن لابتوب',
                'item_name_en' => 'Laptop Charger',
                'barcode' => '1010101010101',
                'model' => 'AC-65W',
                'unit' => 'قطعة',
                'category_id' => null,
                'supplier_id' => $supplier?->id,
                'quantity' => 50.00,
                'minimum_limit' => 8.00,
                'reorder_limit' => 15.00,
                'unit_price' => 120.00,
                'first_purchase_price' => 120.00,
                'second_purchase_price' => 118.00,
                'third_purchase_price' => 115.00,
                'first_sale_price' => 150.00,
                'second_sale_price' => 145.00,
                'third_sale_price' => 140.00,
                'notes' => '65W universal laptop charger with multiple tips',
                'active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
        ];

        foreach ($inventoryItems as $itemData) {
            InventoryItem::firstOrCreate([
                'item_number' => $itemData['item_number']
            ], $itemData);
        }

        $this->command->info('✅ Inventory Items seeded successfully!');
    }
}
