<?php

namespace Modules\Inventory\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Inventory\Models\Item;
use Modules\Inventory\Models\Unit;
use Modules\Users\Models\User;
use Modules\Companies\Models\Company;
use Carbon\Carbon;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get required data
        $user = User::first();
        $company = Company::first();
        $units = Unit::all();

        if (!$user || !$company || $units->isEmpty()) {
            $this->command->warn('⚠️  Required data not found. Please seed Users, Companies, and Units first.');
            return;
        }

        $pieceUnit = $units->where('code', 'PCS')->first();
        $kgUnit = $units->where('code', 'KG')->first();
        $literUnit = $units->where('code', 'LTR')->first();
        $cartonUnit = $units->where('code', 'CTN')->first();
        $meterUnit = $units->where('code', 'MTR')->first();

        $items = [
            [
                'user_id' => $user->id,
                'company_id' => $company->id,
                'unit_id' => $pieceUnit?->id,
                'parent_id' => null,
                'item_number' => 'ITM-001',
                'code' => 'LAP-001',
                'catalog_number' => 'CAT-LAP-001',
                'name' => 'Laptop Dell Inspiron 15',
                'name_ar' => 'لابتوب ديل إنسبايرون 15',
                'description' => 'Dell Inspiron 15 3000 Series laptop with Intel Core i5 processor',
                'description_ar' => 'لابتوب ديل إنسبايرون 15 سلسلة 3000 مع معالج إنتل كور i5',
                'model' => 'Inspiron 15 3000',
                // unit_name removed - available via relationship
                'type' => 'product',
                'quantity' => 50.00,
                'balance' => 50.00,
                'minimum_limit' => 10.00,
                'maximum_limit' => 100.00,
                'reorder_limit' => 15.00,
                'max_reorder_limit' => 80.00,
                'cost_price' => 2500.00,
                'purchase_price' => 2500.00,
                'first_purchase_price' => 2500.00,
                'second_purchase_price' => 2450.00,
                'third_purchase_price' => 2400.00,
                'purchase_discount_rate' => 5.00,
                'purchase_prices_include_vat' => false,
                'sale_price' => 3200.00,
                'minimum_sale_price' => 2800.00,
                'first_sale_price' => 3200.00,
                'second_sale_price' => 3100.00,
                'third_sale_price' => 3000.00,
                'sale_discount_rate' => 10.00,
                'maximum_sale_discount_rate' => 15.00,
                'minimum_allowed_sale_price' => 2700.00,
                'sale_prices_include_vat' => true,
                'item_subject_to_vat' => true,
                'notes' => 'High-performance laptop for business use',
                'barcode' => '1234567890123',
                'barcode_type' => 'EAN13',
                'expiry_date' => null,
                'image' => null,
                'color' => 'Black',
                'length' => 35.80,
                'width' => 24.70,
                'height' => 2.30,
                'item_type' => 'goods',
                'active' => true,
                'stock_tracking' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'user_id' => $user->id,
                'company_id' => $company->id,
                'unit_id' => $pieceUnit?->id,
                'parent_id' => null,
                'item_number' => 'ITM-002',
                'code' => 'MON-001',
                'catalog_number' => 'CAT-MON-001',
                'name' => 'Monitor Samsung 24 inch',
                'name_ar' => 'شاشة سامسونج 24 بوصة',
                'description' => 'Samsung 24-inch Full HD LED monitor with HDMI connectivity',
                'description_ar' => 'شاشة سامسونج 24 بوصة عالية الدقة LED مع منفذ HDMI',
                'model' => 'S24F350FH',
                // unit_name removed - available via relationship
                'type' => 'product',
                'quantity' => 75.00,
                'balance' => 75.00,
                'minimum_limit' => 15.00,
                'maximum_limit' => 150.00,
                'reorder_limit' => 20.00,
                'max_reorder_limit' => 120.00,
                'cost_price' => 450.00,
                'purchase_price' => 450.00,
                'first_purchase_price' => 450.00,
                'second_purchase_price' => 440.00,
                'third_purchase_price' => 430.00,
                'purchase_discount_rate' => 3.00,
                'purchase_prices_include_vat' => false,
                'sale_price' => 580.00,
                'minimum_sale_price' => 500.00,
                'first_sale_price' => 580.00,
                'second_sale_price' => 560.00,
                'third_sale_price' => 540.00,
                'sale_discount_rate' => 8.00,
                'maximum_sale_discount_rate' => 12.00,
                'minimum_allowed_sale_price' => 480.00,
                'sale_prices_include_vat' => true,
                'item_subject_to_vat' => true,
                'notes' => 'Professional monitor for office use',
                'barcode' => '2345678901234',
                'barcode_type' => 'EAN13',
                'expiry_date' => null,
                'image' => null,
                'color' => 'Black',
                'length' => 54.00,
                'width' => 32.00,
                'height' => 4.50,
                'item_type' => 'goods',
                'active' => true,
                'stock_tracking' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'user_id' => $user->id,
                'company_id' => $company->id,
                'unit_id' => $kgUnit?->id,
                'parent_id' => null,
                'item_number' => 'ITM-003',
                'code' => 'STEEL-001',
                'catalog_number' => 'CAT-STEEL-001',
                'name' => 'Steel Rods 12mm',
                'name_ar' => 'حديد تسليح 12 ملم',
                'description' => 'High-grade steel reinforcement rods 12mm diameter',
                'description_ar' => 'حديد تسليح عالي الجودة قطر 12 ملم',
                'model' => 'Grade 60',
                // unit_name removed - available via relationship
                'type' => 'raw_material',
                'quantity' => 5000.000,
                'balance' => 5000.000,
                'minimum_limit' => 1000.000,
                'maximum_limit' => 10000.000,
                'reorder_limit' => 1500.000,
                'max_reorder_limit' => 8000.000,
                'cost_price' => 3.50,
                'purchase_price' => 3.50,
                'first_purchase_price' => 3.50,
                'second_purchase_price' => 3.45,
                'third_purchase_price' => 3.40,
                'purchase_discount_rate' => 2.00,
                'purchase_prices_include_vat' => false,
                'sale_price' => 4.20,
                'minimum_sale_price' => 3.80,
                'first_sale_price' => 4.20,
                'second_sale_price' => 4.10,
                'third_sale_price' => 4.00,
                'sale_discount_rate' => 5.00,
                'maximum_sale_discount_rate' => 8.00,
                'minimum_allowed_sale_price' => 3.70,
                'sale_prices_include_vat' => true,
                'item_subject_to_vat' => true,
                'notes' => 'Construction grade steel rods',
                'barcode' => '3456789012345',
                'barcode_type' => 'EAN13',
                'expiry_date' => null,
                'image' => null,
                'color' => 'Silver',
                'length' => 1200.00,
                'width' => 1.20,
                'height' => 1.20,
                'item_type' => 'goods',
                'active' => true,
                'stock_tracking' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'user_id' => $user->id,
                'company_id' => $company->id,
                'unit_id' => $literUnit?->id,
                'parent_id' => null,
                'item_number' => 'ITM-004',
                'code' => 'PAINT-001',
                'catalog_number' => 'CAT-PAINT-001',
                'name' => 'White Wall Paint',
                'name_ar' => 'دهان أبيض للجدران',
                'description' => 'Premium quality white wall paint for interior use',
                'description_ar' => 'دهان أبيض عالي الجودة للاستخدام الداخلي',
                'model' => 'Premium White',
                // unit_name removed - available via relationship
                'type' => 'material',
                'quantity' => 500.000,
                'balance' => 500.000,
                'minimum_limit' => 100.000,
                'maximum_limit' => 1000.000,
                'reorder_limit' => 150.000,
                'max_reorder_limit' => 800.000,
                'cost_price' => 25.00,
                'purchase_price' => 25.00,
                'first_purchase_price' => 25.00,
                'second_purchase_price' => 24.50,
                'third_purchase_price' => 24.00,
                'purchase_discount_rate' => 4.00,
                'purchase_prices_include_vat' => false,
                'sale_price' => 35.00,
                'minimum_sale_price' => 30.00,
                'first_sale_price' => 35.00,
                'second_sale_price' => 33.00,
                'third_sale_price' => 31.00,
                'sale_discount_rate' => 6.00,
                'maximum_sale_discount_rate' => 10.00,
                'minimum_allowed_sale_price' => 28.00,
                'sale_prices_include_vat' => true,
                'item_subject_to_vat' => true,
                'notes' => 'Eco-friendly paint with low VOC',
                'barcode' => '4567890123456',
                'barcode_type' => 'EAN13',
                'expiry_date' => Carbon::now()->addYears(2),
                'image' => null,
                'color' => 'White',
                'length' => null,
                'width' => null,
                'height' => null,
                'item_type' => 'goods',
                'active' => true,
                'stock_tracking' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
            [
                'user_id' => $user->id,
                'company_id' => $company->id,
                'unit_id' => $cartonUnit?->id,
                'parent_id' => null,
                'item_number' => 'ITM-005',
                'code' => 'PAPER-001',
                'catalog_number' => 'CAT-PAPER-001',
                'name' => 'A4 Copy Paper',
                'name_ar' => 'ورق طباعة A4',
                'description' => 'High-quality A4 copy paper 80gsm, 500 sheets per ream',
                'description_ar' => 'ورق طباعة عالي الجودة A4 وزن 80 جرام، 500 ورقة في الحزمة',
                'model' => '80GSM',
                // unit_name removed - available via relationship
                'type' => 'product',
                'quantity' => 200.00,
                'balance' => 200.00,
                'minimum_limit' => 50.00,
                'maximum_limit' => 500.00,
                'reorder_limit' => 75.00,
                'max_reorder_limit' => 400.00,
                'cost_price' => 120.00,
                'purchase_price' => 120.00,
                'first_purchase_price' => 120.00,
                'second_purchase_price' => 118.00,
                'third_purchase_price' => 115.00,
                'purchase_discount_rate' => 3.00,
                'purchase_prices_include_vat' => false,
                'sale_price' => 150.00,
                'minimum_sale_price' => 135.00,
                'first_sale_price' => 150.00,
                'second_sale_price' => 145.00,
                'third_sale_price' => 140.00,
                'sale_discount_rate' => 5.00,
                'maximum_sale_discount_rate' => 8.00,
                'minimum_allowed_sale_price' => 130.00,
                'sale_prices_include_vat' => true,
                'item_subject_to_vat' => true,
                'notes' => 'Each carton contains 10 reams (5000 sheets)',
                'barcode' => '5678901234567',
                'barcode_type' => 'EAN13',
                'expiry_date' => null,
                'image' => null,
                'color' => 'White',
                'length' => 50.00,
                'width' => 30.00,
                'height' => 25.00,
                'item_type' => 'goods',
                'active' => true,
                'stock_tracking' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
            ],
        ];

        foreach ($items as $itemData) {
            Item::create($itemData);
        }

        $this->command->info('✅ Items seeded successfully!');
    }
}
