<?php

namespace Modules\Sales\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Sales\Models\Sale;
use Carbon\Carbon;

class SaleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if employees exist, if not use null
        $employeeId = \Modules\HumanResources\Models\Employee::first()?->id;

        $sales = [
            // Incoming Orders
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 1,
                'journal_id' => null,
                'journal_number' => 1001,
                'invoice_number' => 'INV-000001',
                'time' => '10:30:00',
                'due_date' => Carbon::now()->subDays(15),
                'type' => 'incoming_order',
                'status' => 'approved',
                'cash_paid' => 0.00,
                'checks_paid' => 0.00,
                'allowed_discount' => 50.00,
                'total_without_tax' => 950.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 142.50,
                'remaining_balance' => 1092.50,
                'exchange_rate' => 1.0000,
                'total_foreign' => 1092.50,
                'total_local' => 1092.50,
                'total_amount' => 1092.50,
                'notes' => 'First incoming order - Electronics',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 2,
                'journal_id' => null,
                'journal_number' => 1002,
                'invoice_number' => 'INV-000002',
                'time' => '11:15:00',
                'due_date' => Carbon::now()->subDays(10),
                'type' => 'incoming_order',
                'status' => 'sent',
                'cash_paid' => 500.00,
                'checks_paid' => 0.00,
                'allowed_discount' => 100.00,
                'total_without_tax' => 900.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 135.00,
                'remaining_balance' => 535.00,
                'exchange_rate' => 1.0000,
                'total_foreign' => 1035.00,
                'total_local' => 1035.00,
                'total_amount' => 1035.00,
                'notes' => 'Partial payment received',
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // Quotations
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 3,
                'journal_id' => null,
                'journal_number' => 2001,
                'invoice_number' => 'QUO-000001',
                'time' => '09:00:00',
                'due_date' => Carbon::now()->addDays(10),
                'type' => 'quotation',
                'status' => 'draft',
                'cash_paid' => 0.00,
                'checks_paid' => 0.00,
                'allowed_discount' => 0.00,
                'total_without_tax' => 2500.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 375.00,
                'remaining_balance' => 2875.00,
                'exchange_rate' => 1.0000,
                'total_foreign' => 2875.00,
                'total_local' => 2875.00,
                'total_amount' => 2875.00,
                'notes' => 'Quotation for office furniture',
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // Invoices
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 1,
                'journal_id' => null,
                'journal_number' => 3001,
                'invoice_number' => 'INV-000003',
                'time' => '14:30:00',
                'due_date' => Carbon::now()->addDays(15),
                'type' => 'invoice',
                'status' => 'approved',
                'cash_paid' => 1500.00,
                'checks_paid' => 500.00,
                'allowed_discount' => 200.00,
                'total_without_tax' => 3800.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 570.00,
                'remaining_balance' => 2370.00,
                'exchange_rate' => 1.0000,
                'total_foreign' => 4370.00,
                'total_local' => 4370.00,
                'total_amount' => 4370.00,
                'notes' => 'Invoice with partial payment',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 2,
                'journal_id' => null,
                'journal_number' => 3002,
                'invoice_number' => 'INV-000004',
                'time' => '16:00:00',
                'due_date' => Carbon::now()->addDays(20),
                'type' => 'invoice',
                'status' => 'invoiced',
                'cash_paid' => 1200.00,
                'checks_paid' => 0.00,
                'allowed_discount' => 0.00,
                'total_without_tax' => 1200.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 180.00,
                'remaining_balance' => 180.00,
                'exchange_rate' => 1.0000,
                'total_foreign' => 1380.00,
                'total_local' => 1380.00,
                'total_amount' => 1380.00,
                'notes' => 'Fully paid invoice',
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // Outgoing Shipments
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 3,
                'journal_id' => null,
                'journal_number' => 4001,
                'invoice_number' => 'SHIP-000001',
                'time' => '08:30:00',
                'due_date' => Carbon::now()->addDays(25),
                'type' => 'outgoing_shipment',
                'status' => 'sent',
                'cash_paid' => 0.00,
                'checks_paid' => 0.00,
                'allowed_discount' => 150.00,
                'total_without_tax' => 4850.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 727.50,
                'remaining_balance' => 5577.50,
                'exchange_rate' => 1.0000,
                'total_foreign' => 5577.50,
                'total_local' => 5577.50,
                'total_amount' => 5577.50,
                'notes' => 'Shipment to customer warehouse',
                'created_by' => 1,
                'updated_by' => 1,
            ],

            // Services
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'currency_id' => 1,
                'employee_id' => $employeeId,
                'customer_id' => 1,
                'journal_id' => null,
                'journal_number' => 5001,
                'invoice_number' => 'SRV-000001',
                'time' => '13:00:00',
                'due_date' => Carbon::now()->addDays(30),
                'type' => 'service',
                'status' => 'approved',
                'cash_paid' => 800.00,
                'checks_paid' => 0.00,
                'allowed_discount' => 0.00,
                'total_without_tax' => 800.00,
                'tax_percentage' => 15.00,
                'tax_amount' => 120.00,
                'remaining_balance' => 120.00,
                'exchange_rate' => 1.0000,
                'total_foreign' => 920.00,
                'total_local' => 920.00,
                'total_amount' => 920.00,
                'notes' => 'Consulting service invoice',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        foreach ($sales as $sale) {
            Sale::updateOrCreate(
                ['invoice_number' => $sale['invoice_number']],
                $sale
            );
        }

        $this->command->info('Sales seeded successfully!');
    }
}

