<?php

namespace Modules\Suppliers\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Suppliers\Models\SalesRepresentative;

class SalesRepresentativeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $representatives = [
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'department_id' => null,
                'representative_number' => 'REP-0001',
                'employee_number' => 'EMP-001',
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'full_name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@example.com',
                'phone' => '+962-6-1234567',
                'mobile' => '+962-79-1234567',
                'emergency_contact' => '+962-79-7654321',
                'address' => 'Amman, Jordan',
                'country_id' => 1,
                'region_id' => 1,
                'city_id' => 1,
                'hire_date' => '2023-01-15',
                'termination_date' => null,
                'employment_type' => 'full_time',
                'base_salary' => 1500.00,
                'commission_rate' => 5.00,
                'sales_target' => 50000.00,
                'current_sales' => 35000.00,
                'total_commission' => 1750.00,
                'customers_count' => 25,
                'suppliers_count' => 10,
                'territory' => json_encode(['Amman', 'Zarqa', 'Irbid']),
                'specialization' => json_encode(['Electronics', 'Home Appliances']),
                'notes' => 'Top performing sales representative',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'department_id' => null,
                'representative_number' => 'REP-0002',
                'employee_number' => 'EMP-002',
                'first_name' => 'Fatima',
                'last_name' => 'Ali',
                'full_name' => 'Fatima Ali',
                'email' => 'fatima.ali@example.com',
                'phone' => '+962-6-2345678',
                'mobile' => '+962-79-2345678',
                'emergency_contact' => '+962-79-8765432',
                'address' => 'Irbid, Jordan',
                'country_id' => 1,
                'region_id' => 2,
                'city_id' => 2,
                'hire_date' => '2023-03-20',
                'termination_date' => null,
                'employment_type' => 'full_time',
                'base_salary' => 1400.00,
                'commission_rate' => 4.50,
                'sales_target' => 45000.00,
                'current_sales' => 30000.00,
                'total_commission' => 1350.00,
                'customers_count' => 20,
                'suppliers_count' => 8,
                'territory' => json_encode(['Irbid', 'Ajloun', 'Jerash']),
                'specialization' => json_encode(['Furniture', 'Office Supplies']),
                'notes' => 'Excellent customer relations',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'department_id' => null,
                'representative_number' => 'REP-0003',
                'employee_number' => 'EMP-003',
                'first_name' => 'Mohammed',
                'last_name' => 'Khalil',
                'full_name' => 'Mohammed Khalil',
                'email' => 'mohammed.khalil@example.com',
                'phone' => '+962-6-3456789',
                'mobile' => '+962-79-3456789',
                'emergency_contact' => '+962-79-9876543',
                'address' => 'Aqaba, Jordan',
                'country_id' => 1,
                'region_id' => 3,
                'city_id' => 3,
                'hire_date' => '2023-06-10',
                'termination_date' => null,
                'employment_type' => 'full_time',
                'base_salary' => 1300.00,
                'commission_rate' => 4.00,
                'sales_target' => 40000.00,
                'current_sales' => 28000.00,
                'total_commission' => 1120.00,
                'customers_count' => 18,
                'suppliers_count' => 7,
                'territory' => json_encode(['Aqaba', 'Maan', 'Tafilah']),
                'specialization' => json_encode(['Construction Materials', 'Hardware']),
                'notes' => 'Strong in southern region',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'department_id' => null,
                'representative_number' => 'REP-0004',
                'employee_number' => 'EMP-004',
                'first_name' => 'Sara',
                'last_name' => 'Mahmoud',
                'full_name' => 'Sara Mahmoud',
                'email' => 'sara.mahmoud@example.com',
                'phone' => '+962-6-4567890',
                'mobile' => '+962-79-4567890',
                'emergency_contact' => '+962-79-0987654',
                'address' => 'Zarqa, Jordan',
                'country_id' => 1,
                'region_id' => 1,
                'city_id' => 4,
                'hire_date' => '2023-09-01',
                'termination_date' => null,
                'employment_type' => 'part_time',
                'base_salary' => 800.00,
                'commission_rate' => 6.00,
                'sales_target' => 25000.00,
                'current_sales' => 18000.00,
                'total_commission' => 1080.00,
                'customers_count' => 12,
                'suppliers_count' => 5,
                'territory' => json_encode(['Zarqa', 'Russeifa']),
                'specialization' => json_encode(['Textiles', 'Fashion']),
                'notes' => 'Part-time representative with good performance',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 1,
                'company_id' => 1,
                'branch_id' => 1,
                'department_id' => null,
                'representative_number' => 'REP-0005',
                'employee_number' => 'EMP-005',
                'first_name' => 'Khaled',
                'last_name' => 'Omar',
                'full_name' => 'Khaled Omar',
                'email' => 'khaled.omar@example.com',
                'phone' => '+962-6-5678901',
                'mobile' => '+962-79-5678901',
                'emergency_contact' => '+962-79-1098765',
                'address' => 'Amman, Jordan',
                'country_id' => 1,
                'region_id' => 1,
                'city_id' => 1,
                'hire_date' => '2022-11-15',
                'termination_date' => null,
                'employment_type' => 'contract',
                'base_salary' => 1200.00,
                'commission_rate' => 5.50,
                'sales_target' => 35000.00,
                'current_sales' => 25000.00,
                'total_commission' => 1375.00,
                'customers_count' => 15,
                'suppliers_count' => 6,
                'territory' => json_encode(['Amman']),
                'specialization' => json_encode(['Food & Beverages', 'FMCG']),
                'notes' => 'Contract-based representative',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        foreach ($representatives as $representative) {
            SalesRepresentative::updateOrCreate(
                ['representative_number' => $representative['representative_number']],
                $representative
            );
        }

        $this->command->info('Sales representatives seeded successfully!');
    }
}

